"""add new fields

Revision ID: 8831682c0598
Revises: 9424f7fd0609
Create Date: 2023-06-14 17:00:08.773083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8831682c0598'
down_revision = '9424f7fd0609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_type', sa.String(length=256), nullable=True))
        batch_op.create_index(batch_op.f('ix_requests_auth_type'), ['auth_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requests_auth_type'))
        batch_op.drop_column('auth_type')

    # ### end Alembic commands ###
