"""empty message

Revision ID: d25a33815850
Revises: 0110bf34cb05
Create Date: 2023-05-31 14:08:14.877844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25a33815850'
down_revision = '0110bf34cb05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=256), nullable=True))
        batch_op.drop_index('ix_requests_addresss')
        batch_op.create_index(batch_op.f('ix_requests_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_name'), ['name'], unique=False)
        batch_op.drop_column('addresss')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('addresss', sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_index(batch_op.f('ix_requests_name'))
        batch_op.drop_index(batch_op.f('ix_requests_address'))
        batch_op.create_index('ix_requests_addresss', ['addresss'], unique=False)
        batch_op.drop_column('name')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
