"""Add comments, devices, auty type

Revision ID: d95398046931
Revises: d25a33815850
Create Date: 2023-06-13 10:51:31.508157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd95398046931'
down_revision = 'd25a33815850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendors_name'), ['name'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_name'), ['name'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connection_type', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('device', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('base', sa.String(length=256), nullable=True))
        batch_op.create_index(batch_op.f('ix_requests_base'), ['base'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_connection_type'), ['connection_type'], unique=False)
        batch_op.create_foreign_key(None, 'devices', ['device'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_requests_connection_type'))
        batch_op.drop_index(batch_op.f('ix_requests_base'))
        batch_op.drop_column('base')
        batch_op.drop_column('device')
        batch_op.drop_column('connection_type')

    op.drop_table('comments')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_name'))

    op.drop_table('devices')
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_name'))

    op.drop_table('vendors')
    # ### end Alembic commands ###
